seed_everything: 42

model:
  class_path: spherinator.models.VariationalAutoencoder
  init_args:
    encoder:
      class_path: spherinator.models.ConvolutionalEncoder2D
      init_args:
        input_dim: [3, 128, 128]
        output_dim: 128
        cnn_layers:
          - class_path: spherinator.models.ConsecutiveConv2DLayer
            init_args:
              kernel_size: 3
              stride: 1
              padding: 0
              out_channels: [16, 20, 24] 
          - class_path: spherinator.models.ConsecutiveConv2DLayer
            init_args:
              kernel_size: 4
              stride: 2
              padding: 0
              out_channels: [64, 128]
    decoder:
      class_path: spherinator.models.ConvolutionalDecoder2D
      init_args:
        input_dim: 3
        output_dim: [3, 128, 128]
        cnn_input_dim: [128, 28, 28]
        cnn_layers:
          - class_path: spherinator.models.ConsecutiveConvTranspose2DLayer
            init_args:
              kernel_size: 5
              stride: 2
              padding: 0
              out_channels: [64]
          - class_path: spherinator.models.ConsecutiveConvTranspose2DLayer
            init_args:
              kernel_size: 6
              stride: 2
              padding: 0
              out_channels: [24]
          - class_path: spherinator.models.ConsecutiveConvTranspose2DLayer
            init_args:
              kernel_size: 3
              stride: 1
              padding: 0
              out_channels: [20, 16, 3]
              activation: null
    z_dim: 3
    beta: 1.0e-3
    encoder_out_dim: 128

data:
  class_path: spherinator.data.ParquetDataModule
  init_args:
    data_directory: data/illustris/parquet
    data_column: data
    normalize: minmax
    batch_size: 512
    num_workers: 4

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
 class_path: lightning.pytorch.cli.ReduceLROnPlateau
 init_args:
   mode: min
   factor: 0.1
   patience: 25
   cooldown: 5
   min_lr: 1.e-7
   monitor: train_loss

trainer:
  max_epochs: 10
  accelerator: gpu
  devices: auto
  precision: 16-mixed
  log_every_n_steps: 1
