seed_everything: 42
# ckpt_path: illustris/no8e8ygy/checkpoints/epoch=1571-train_loss=0.01.ckpt

model:
  class_path: spherinator.models.VariationalAutoencoder
  init_args:
    encoder:
      class_path: spherinator.models.ConvolutionalEncoder2D
      init_args:
        input_dim: [3, 128, 128]
        output_dim: 12
        cnn_layers:
          - class_path: spherinator.models.ConsecutiveConv2DLayer
            init_args:
              kernel_size: 5
              stride: 2
              padding: 2
              out_channels: [6, 9, 12]
    decoder:
      class_path: spherinator.models.ConvolutionalDecoder2D
      init_args:
        input_dim: 3
        output_dim: [3, 128, 128]
        cnn_input_dim: [12, 16, 16]
        cnn_layers:
          - class_path: spherinator.models.ConsecutiveConvTranspose2DLayer
            init_args:
              kernel_size: 5
              stride: 2
              padding: 2
              output_padding: 1
              out_channels: [9, 6]
          - class_path: spherinator.models.ConsecutiveConvTranspose2DLayer
            init_args:
              kernel_size: 5
              stride: 2
              padding: 2
              output_padding: 1
              out_channels: [3]
              activation: null
    z_dim: 3
    beta: 1.0e-3
    encoder_out_dim: 12

data:
  class_path: spherinator.data.ParquetDataModule
  init_args:
    data_directory: data/illustris/parquet
    data_column: data
    normalize: minmax
    batch_size: 512
    num_workers: 4

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
 class_path: lightning.pytorch.cli.ReduceLROnPlateau
 init_args:
   mode: min
   factor: 0.1
   patience: 25
   cooldown: 5
   min_lr: 1.e-7
   monitor: train_loss
   verbose: True

trainer:
  max_epochs: -1
  accelerator: gpu
  devices: auto
  precision: 16-mixed
  log_every_n_steps: 1
  # profiler: simple
  # enable_progress_bar: False
  # enable_model_summary: False

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: train_loss
        filename: "{epoch}-{train_loss:.2f}"
        save_top_k: 1
        mode: min
        every_n_epochs: 1
    - class_path: spherinator.callbacks.LogReconstructionCallback
      init_args:
        samples: 6

  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: illustris
      log_model: True
      entity: ain-space
      tags:
        - vae
