root_path: HiPSter
overwrite: true
verbose: true

html:
  # url: http://localhost:8083
  url: https://space.h-its.org/Gaia
  title: HiPSter representation of Gaia XP DR3
  aladin_lite_version: latest

tasks:
  - class_path: hipster.HiPSGenerator
    init_args:
      decoder:
        model_path: data/gaia/models/full_trained/decoder.onnx
      image_maker:
        class_path: hipster.SpectrumPlotter
        init_args:
          wavelengths:
            start: 336
            stop: 1021
            step: 2
          ylim: [0, 1]
          margin: 0.02
          figsize_in_pixel: 128
          flip: True
      hips_id: Gaia1
      hips_name: Gaia XP DR3 model spectrum
      hips_path: gaia/model_spectrum
      max_order: 2
      hierarchy: 4
  - class_path: hipster.VOTableGenerator
    init_args:
      encoder:
        model_path: data/gaia/models/full_trained/encoder.onnx
      data_directory: data/gaia/parquet
      data_column: flux
      dataset: gaia
      output_file: gaia.vot
      color: red
      shape: circle
      size: 10
